spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gidmovie?autoReconnect=true&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2021JavaForTest@gmail.com
    password: forTest2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
gidmovie:
  upload:
    path: C:/Users/User/IdeaProjects/GidMovie/img/